In [4]:
import pandas as pd
import numpy as np

In [16]:
dataset = pd.read_csv('xor.dat', header = None)

In [19]:
dataset

0    1  2
0  0.0  0.0  0
1  1.0  0.0  1
2  0.0  1.0  1
3  1.0  1.0  0

In [147]:
def get_parameters(dataset):
    train = dataset.sample(frac=1)
    X = train.drop(2, axis=1)
    Y = train[2]

    # One hot encoding for Y
    Y = pd.get_dummies(Y)

    num_classes = Y.shape[1]
    num_features = X.shape[1]
    N = X.shape[0]

    # Weights 
    W = np.random.rand(num_features, num_classes)
    b = np.zeros(num_classes)
    
    return X, Y, W, b, N, num_classes, num_features

In [148]:
def softmax(logits):
    '''
        Computes the softmax function value
    '''
    activation = []
    for index in range(0, len(logits)):
        exp_sum = 0
        for val in logits[index]:
            exp_sum += np.exp(val)
        activation.append([np.exp(value) / exp_sum for value in logits[index]])
        
    return activation

In [149]:
pre_activation.shape

(300, 2)

In [150]:
def compute_pre_act(input_x, weights, bias):
    '''
        Compute pre activation i.e. f = X*W + b
    '''
    
    return np.dot(input_x, weights) + bias

In [164]:
#XT = np.transpose(X)
X, Y, W, b, N, num_classes, num_weights = get_parameters(dataset)

# Compute activation in forward propogation
pre_activation = compute_pre_act(X, W, b)

p = softmax(pre_activation)

p

[[0.2988471024610757, 0.7011528975389243],
 [0.3819850083703233, 0.6180149916296768],
 [0.40813935339684804, 0.5918606466031521],
 [0.5, 0.5]]

In [165]:
# Gradient of loss wrt pre activation Wx + b.
grad_loss = np.subtract(p, Y)
grad_loss

0         1
3 -0.701153  0.701153
2  0.381985 -0.381985
1  0.408139 -0.408139
0 -0.500000  0.500000

In [166]:
# Gradient for weights = XT * (1/N)grad_loss + learn_rate * W
XT = np.transpose(X)
learn_rate = 0.001

W_grad = np.dot(XT, np.divide(grad_loss, N)) + np.multiply(W, learn_rate)

W_grad

# Gradient for bias = 1/N * summation ()

array([[-0.07265623,  0.07422221],
       [-0.07950053,  0.08056455]])

In [178]:
def compute_loss(post_act, num_instances, learning_rate, Weights, Y_values):
    '''
        Compute loss = -1/N * (summation(log(post_act[i,Yi]))) + (learning_rate / 2) * (summation((Weights[d, k]) ^ 2)
    '''
    # First part without constant
    log_summation = 0
    for i in range(0, len(post_act)):
        log_summation += np.log(post_act[Y_values[i]])
        
    # Second part without constant    
    weights_summation = 0
    for d in range(0, len(Weights)):
        for k in range(0, len(Weights[0])):
            weights_summation += np.square(Weights[d][k])
            
    loss = log_summation * (-1/num_instances) + (learning_rate/2) * weights_summation
    
    return loss

In [168]:
def gradient_checking(analytical_grad):
    '''
        Compute the numerical gradient for each weight and check if difference is < 1e-4 for all.
    '''
    epsilon = 0.001
    
    log_p = np.multiply(Y, np.log(p))
    
    # For each row / data point, get loss with weight + epsilon and weight - epsilon
    for y_ind in range(0, len(log_p.shape[1])):
        L_plus = compute_loss(p[y_ind], N, learn_rate, np.add(W, epsilon))
        L_minus = compute_loss(p[y_ind], N, learn_rate, np.subtract(W, epsilon), Y.iloc[y_ind])
    
        numerical_grad = 0
    
    if np.abs(numerical_grad - analytical_grad) < (1 * np.power(10, -4)):
        return True

In [194]:
np.subtract(W, 0.001)

array([[0.59615905, 0.9678216 ],
       [0.29044213, 0.77157348]])

In [191]:
for y_ind in range(0, len(Y)):
    print(compute_loss(p[y_ind], N, learn_rate, W, Y.iloc[y_ind]))

0.3917016366703075
0.36189263119864157
0.356146180384105
0.34756210153667344


3    1
2    0
1    0
0    1
Name: 0, dtype: uint8

In [154]:
# 1b
dataset_spiral = pd.read_csv('spiral_train.dat', header=None)

In [155]:
X, Y, W, b, N, num_classes, num_weights = get_parameters(dataset_spiral)

# Compute activation in forward propogation
pre_activation = compute_pre_act(X, W, b)

p = softmax(pre_activation)

In [156]:
# Gradient of loss wrt pre activation Wx + b.
grad_loss = np.subtract(p, Y)
grad_loss

0         1         2
24  -0.676437  0.326065  0.350373
278  0.367151  0.361796 -0.728947
93  -0.617728  0.399298  0.218430
159  0.296441 -0.723896  0.427454
18  -0.678117  0.319030  0.359087
5   -0.669465  0.328544  0.340921
235  0.352386  0.366542 -0.718928
286  0.347930  0.324548 -0.672478
299  0.293485  0.257899 -0.551384
181  0.276691 -0.736109  0.459417
273  0.355830  0.342016 -0.697846
160  0.295189 -0.725142  0.429953
52  -0.670353  0.346545  0.323808
223  0.341604  0.352069 -0.693673
238  0.354285  0.369268 -0.723553
61  -0.657277  0.369434  0.287843
86  -0.620876  0.404349  0.216527
156  0.295567 -0.721834  0.426268
100  0.333333 -0.666667  0.333333
208  0.333274  0.336068 -0.669342
162  0.289533 -0.726322  0.436789
168  0.286244 -0.725192  0.438948
289  0.311371  0.278660 -0.590031
193  0.285675 -0.712078  0.426404
271  0.371739  0.381675 -0.753414
233  0.349993  0.364316 -0.714310
132  0.335113 -0.675201  0.340087
115  0.337782 -0.665087  0.327305
255  0.363460  0.369751 -0.733210
75  -0.638994  0.397917  0.241078
..        ...       ...       ...
190  0.281044 -0.721658  0.440614
6   -0.670536  0.327712  0.342825
218  0.341168  0.349230 -0.690398
30  -0.681543  0.319292  0.362251
261  0.366428  0.373407 -0.739835
149  0.312488 -0.706968  0.394480
117  0.339394 -0.663105  0.323711
154  0.302641 -0.717316  0.414675
37  -0.675219  0.333249  0.341970
151  0.300231 -0.716758  0.416527
60  -0.660779  0.364042  0.296737
173  0.281085 -0.734549  0.453464
54  -0.664794  0.355792  0.309002
291  0.329059  0.298012 -0.627072
124  0.339573 -0.665631  0.326058
293  0.331291  0.300113 -0.631405
143  0.315821 -0.701497  0.385676
8   -0.671739  0.325630  0.346109
128  0.332901 -0.676883  0.343982
125  0.337582 -0.669156  0.331574
230  0.342472  0.356145 -0.698618
283  0.324742  0.295321 -0.620063
226  0.343298  0.355195 -0.698493
36  -0.675738  0.332017  0.343721
174  0.280193 -0.736334  0.456141
281  0.335619  0.309321 -0.644940
263  0.365148  0.367154 -0.732302
130  0.336955 -0.671871  0.334916
210  0.334553  0.338540 -0.673093
59  -0.660152  0.364550  0.295602

[300 rows x 3 columns]

In [158]:
# Gradient for weights = XT * (1/N)grad_loss + learn_rate * W
XT = np.transpose(X)
learn_rate = 0.001

W_grad = np.dot(XT, np.divide(grad_loss, N)) + np.multiply(W, learn_rate)

W_grad

array([[-0.0457932 , -0.0532089 ,  0.10069507],
       [ 0.07510256, -0.11419095,  0.04004541]])

In [211]:
np.multiply(Y, np.log(p)).shape[1]

2

In [201]:
np.log(p)

array([[-1.2078232 , -0.3550293 ],
       [-0.96237392, -0.48124256],
       [-0.89614661, -0.52448407],
       [-0.69314718, -0.69314718]])